name: New Bug Report
description: File a bug report
title: "Product Area: Short description of bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please try to give your issue a good title. Try using the product-area where you are having an issue and a brief description of the problem. Like this:
        - `Dashboards: Template Variables break when I do X` or
        - `Alerting: message templating plus Slack channel breaks when I do X`
  - type: markdown
    attributes:
      value: |
        **HINT:** Have you tried [searching](https://github.com/grafana/grafana/issues) for similar issues? Duplicate issues are common.

        **Are you reporting a security vulnerability?** [Submit it here instead](https://github.com/grafana/grafana/security/policy).
  - type: markdown
    attributes:
      value: |
       #

  - type: textarea
    attributes:
      label: What happened?
      description: "**Hot Tip:** Record your screen and attach it here."
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Did this work before?
      description: "If this worked before, what Grafana version worked correctly?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: How do we reproduce it?
      placeholder: "Steps to reproduce..."
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment (with versions)?
      description: |
        [How do I find my Grafana version info?](https://community.grafana.com/t/how-to-find-your-grafana-version-info-3-different-ways/86857)
      placeholder: "Grafana, OS, and Browser versions..."
      value: |
        Grafana:
        OS:
        Browser:
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Grafana platform?
      description: How are you running/deploying Grafana?
      options:
        - I use Grafana Cloud
        - Docker
        - Kubernetes
        - A package manager (APT, YUM, BREW, etc.)
        - A downloaded binary
        - Other
        - I don't know
    validations:
      required: false
